import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import QueryClientContext from '@/contexts/query-client'

const inter = Inter({ subsets: ['latin'] })
// const inter = Roboto({
//   subsets: ['vietnamese'],
//   variable: '--font-roboto',
//   weight: ['100', '300', '400', '500', '700']
// })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn(inter.className)}>
        <QueryClientContext>{children}</QueryClientContext>
      </body>
    </html>
  )
}
