import QueryClientContext from '@/contexts/query-client'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const inter = Roboto({
  subsets: ['vietnamese'],
  variable: '--font-roboto',
  weight: ['100', '300', '400', '500', '700']
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn(inter.className)}>
        <Toaster position='top-right' />
        <QueryClientContext>{children}</QueryClientContext>
      </body>
    </html>
  )
}
